### ISSUE TITLE
ModuleNotFoundError: No module named 

### ISSUE THREAD

**Issue by Knoxi-Code** [oSquat/mooltipy#24]
```
 mooltipy login set example.com -u user_name
Traceback (most recent call last):
  File "/usr/local/bin/mooltipy", line 33, in <module>
    sys.exit(load_entry_point('mooltipy==1.0.0', 'console_scripts', 'mooltipy')())
  File "/usr/local/bin/mooltipy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mooltipy' 
```
What can i do to fix this ?

**Comment by saagit** [comment]
I reproduced your problem on a fresh Debian 11 installation, but I'm not a packaging expert and I haven't dug into the problem.  However, by playing around I think you can work around your problem by slightly revising the documented "Installation & usage" to change into the unzip'ed directory before installation:
```
$ wget https://github.com/oSquat/mooltipy/archive/refs/heads/master.zip
$ unzip ./master.zip
$ cd mooltipy-master
$ sudo python3 setup.py install
```

A few somewhat unrelated notes for completeness:

1.  It looks like you're beyond this, but a stock Debian system will need to have the Python setup tools installed via `sudo apt install python3-setuptools`.
2. If you are the only user that needs to use mooltipy, you can use `python3 setup.py install --user` to install mooltipy into your home directory (~/.local/...) instead of into needing to use sudo to install into /usr.  You'll need to ensure that you have ~/.local/bin in your shell's path if you do this.
3. Once you get mooltipy running, you may need to add udev rules so the mooltipass will be accessible.

Hope this helps.

**Comment by Knoxi-Code** [comment]
Thanks for the quick help, I will test it later

**Comment by Knoxi-Code** [comment]
Hey this works but now i have the next error

```
An error occurred accessing the mooltipass: 
Mooltipass not found. Is it plugged in?
```

I configuret the udev rules too, but i cant acces.

**Comment by oSquat** [comment]
Good news mooltipy is working. I ran into the same problem after Python upgraded on my system and reinstalling worked for me, but I run mooltipy out of a virtual environment which may be different from the adjustment to the installation procedure. Thank you @saagit for your help, I'll see about updating the readme.

As for the permission thing, can you run mootipy as root? It sees the device then I hope.

**Comment by saagit** [comment]
Just a quick couple of things that may be obvious to some, but not everyone:
1) After configuring udev, you need to either tell udev to reread the rules or simply unplug and replug the Mooltipass to have it use the new rules.
2) Support for the current Mooltipass Mini BLE has not been added to mooltipy (Issue #19).
